version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
    environment:
      - APP_ENV=local
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  nginx:
    image: nginx
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www:cached
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres
    container_name: laravel-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis
    container_name: laravel-redis
    restart: unless-stopped
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge